#!/usr/bin/env bash
# apply-theme-clients.sh — paint mako + fuzzel from an astral-vagabond role JSON
#
# Usage:
#   apply-theme-clients.sh                         # ~/.config/quickshell/astral-vagabond/colors/active-colors.json
#   apply-theme-clients.sh /path/to/roles.json
#
# Reads Theme roles (accent, textPrimary, bgConsole, …) and writes:
#   ~/.config/mako/config          ← rendered from config.tmpl
#   ~/.config/fuzzel/colors.ini    ← included by fuzzel.ini
# then `makoctl reload` if mako is running.
#
# Same Ash-chrome rule as load-wallust-colors.sh: surfaces stay on the JSON
# (Ash unless a role was overridden); only whatever the JSON already tinted
# (accents + text) shows up in notifications and the launcher.
set -euo pipefail

CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
JSON="${1:-${CFG}/quickshell/astral-vagabond/colors/active-colors.json}"
MAKO_TMPL="${CFG}/mako/config.tmpl"
MAKO_OUT="${CFG}/mako/config"
FUZZEL_OUT="${CFG}/fuzzel/colors.ini"

if [[ ! -f "$JSON" ]]; then
    echo "error: palette JSON not found: $JSON" >&2
    exit 1
fi
if [[ ! -f "$MAKO_TMPL" ]]; then
    echo "error: mako template missing: $MAKO_TMPL" >&2
    exit 1
fi

python3 - "$JSON" "$MAKO_TMPL" "$MAKO_OUT" "$FUZZEL_OUT" <<'PY'
import json
import sys
from pathlib import Path

json_path, tmpl_path, mako_out, fuzzel_out = map(Path, sys.argv[1:5])
data = json.loads(json_path.read_text())

FALLBACK = {
    "bgPrimary": "#121212",
    "bgSurface": "#1A1A1A",
    "bgElevated": "#242424",
    "bgConsole": "#161616",
    "accent": "#C8C8C8",
    "accentWarm": "#A3A3A3",
    "accentSoft": "#737373",
    "textPrimary": "#E5E5E5",
    "textSecondary": "#A3A3A3",
    "textMuted": "#6B6B6B",
    "textDim": "#454545",
    "stateCritical": "#E8E8E8",
    "stateSafe": "#8A8A8A",
    "stateWarning": "#B8B8B8",
    "borderActive": "#C8C8C8",
    "borderIdle": "#333333",
    "borderConsole": "#333333",
    "glowConsole": "#555555",
}


def hex6(key: str) -> str:
    raw = str(data.get(key) or FALLBACK[key]).strip()
    if raw.startswith("#"):
        raw = raw[1:]
    raw = raw[:6].upper()
    if len(raw) != 6 or any(c not in "0123456789ABCDEF" for c in raw):
        raw = FALLBACK[key][1:]
    return f"#{raw}"


roles = {key: hex6(key) for key in FALLBACK}

tmpl = tmpl_path.read_text()
for key, value in roles.items():
    tmpl = tmpl.replace("{{" + key + "}}", value)
mako_out.parent.mkdir(parents=True, exist_ok=True)
tmp = mako_out.with_suffix(".config.tmp")
tmp.write_text(tmpl)
tmp.replace(mako_out)

def fuzzel(key: str, alpha: str = "ff") -> str:
    return roles[key][1:].lower() + alpha.lower()


source = str(data.get("_source") or "palette")
colors = f"""# generated by apply-theme-clients.sh from {json_path}
# source: {source} — do not edit; rerun the loader instead
[colors]
background={fuzzel("bgConsole", "f8")}
text={fuzzel("textSecondary")}
message={fuzzel("textSecondary")}
prompt={fuzzel("accent")}
placeholder={fuzzel("textDim")}
input={fuzzel("textPrimary")}
match={fuzzel("accent")}
selection={fuzzel("borderIdle")}
selection-text={fuzzel("textPrimary")}
selection-match={fuzzel("accent")}
counter={fuzzel("textMuted")}
border={fuzzel("accent")}
"""
fuzzel_out.parent.mkdir(parents=True, exist_ok=True)
ftmp = fuzzel_out.with_suffix(".ini.tmp")
ftmp.write_text(colors)
ftmp.replace(fuzzel_out)

print(f"mako:    {mako_out}")
print(f"fuzzel:  {fuzzel_out}")
print(f"  source={source}  accent={roles['accent']}  text={roles['textPrimary']}")
PY

echo "clients: wrote mako + fuzzel from $JSON"

if command -v makoctl >/dev/null 2>&1 && pgrep -u "$USER" -x mako >/dev/null 2>&1; then
    if makoctl reload >/dev/null 2>&1; then
        echo "mako:    reloaded"
    else
        echo "warning: makoctl reload failed" >&2
    fi
else
    echo "mako:    not running — config only"
fi
