#!/usr/bin/env bash
# load-legacy-colors.sh — extract Theme.qml color props into legacy-colors.json
# and (by default) activate them as the live palette Theme.qml reads.
#
# Usage:
#   load-legacy-colors.sh              # extract + activate legacy
#   load-legacy-colors.sh --extract    # only write colors/legacy-colors.json
#   load-legacy-colors.sh --activate   # activate existing legacy-colors.json
#   load-legacy-colors.sh --status     # show which source is active
#
# Theme.qml always watches:  <astral-vagabond>/colors/active-colors.json
# Source marker:             <astral-vagabond>/colors/source   ("legacy" | "wallust")
# Hyprland: also rewrites ~/.config/hypr/hyprland/colors.lua + live hyprctl keywords
# Clients:  mako/config + fuzzel/colors.ini via apply-theme-clients.sh
#
# Extraction is a simple regex over:
#   readonly property color <name>:  "#RRGGBB"
# Hardcoded fallbacks match the Ash monochrome palette if Theme no longer embeds hexes.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ASTRAL_VAGABOND_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
THEME_QML="${ASTRAL_VAGABOND_DIR}/Theme.qml"
COLORS_DIR="${ASTRAL_VAGABOND_DIR}/colors"
LEGACY_JSON="${COLORS_DIR}/legacy-colors.json"
ACTIVE_JSON="${COLORS_DIR}/active-colors.json"
SOURCE_FILE="${COLORS_DIR}/source"

COLOR_KEYS=(
    bgPrimary bgSurface bgElevated
    accent accentWarm accentSoft
    textPrimary textSecondary textMuted textDim
    stateCritical stateSafe stateWarning
    borderActive borderIdle
    bgConsole borderConsole glowConsole
)

declare -A FALLBACK=(
    [bgPrimary]="#121212"
    [bgSurface]="#1A1A1A"
    [bgElevated]="#242424"
    [accent]="#C8C8C8"
    [accentWarm]="#A3A3A3"
    [accentSoft]="#737373"
    [textPrimary]="#E5E5E5"
    [textSecondary]="#A3A3A3"
    [textMuted]="#6B6B6B"
    [textDim]="#454545"
    [stateCritical]="#E8E8E8"
    [stateSafe]="#8A8A8A"
    [stateWarning]="#B8B8B8"
    [borderActive]="#C8C8C8"
    [borderIdle]="#333333"
    [bgConsole]="#161616"
    [borderConsole]="#333333"
    [glowConsole]="#555555"
)

usage() {
    sed -n '2,16p' "$0" | sed 's/^# \?//'
    exit 0
}

normalize_hex() {
    local h="$1"
    h="${h^^}"
    [[ "$h" =~ ^#[0-9A-F]{6}$ ]] || return 1
    printf '%s' "$h"
}

# Populate EXTRACTED via regex find on Theme.qml.
# Supports both:
#   readonly property color accent: "#C8C8C8"
#   "accent": "#C8C8C8"   (inside Theme._defaults map after JSON refactor)
extract_from_theme() {
    local theme="$1"
    declare -gA EXTRACTED=()

    [[ -f "$theme" ]] || return 1

    local line name hex
    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%%//*}"
        if [[ "$line" =~ readonly[[:space:]]+property[[:space:]]+color[[:space:]]+([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*:[[:space:]]*\"(#[0-9A-Fa-f]{6})\" ]]; then
            name="${BASH_REMATCH[1]}"
            hex="$(normalize_hex "${BASH_REMATCH[2]}")" || continue
            EXTRACTED["$name"]="$hex"
        elif [[ "$line" =~ \"([A-Za-z_][A-Za-z0-9_]*)\"[[:space:]]*:[[:space:]]*\"(#[0-9A-Fa-f]{6})\" ]]; then
            name="${BASH_REMATCH[1]}"
            hex="$(normalize_hex "${BASH_REMATCH[2]}")" || continue
            # only accept known Theme color roles
            local known=0 k
            for k in "${COLOR_KEYS[@]}"; do
                if [[ "$k" == "$name" ]]; then known=1; break; fi
            done
            [[ $known -eq 1 ]] || continue
            EXTRACTED["$name"]="$hex"
        fi
    done < "$theme"
}

existing_legacy_value() {
    local key="$1"
    [[ -f "$LEGACY_JSON" ]] || { printf ''; return; }
    python3 -c '
import json, sys
try:
    d = json.load(open(sys.argv[1]))
    v = d.get(sys.argv[2], "")
    print(v if isinstance(v, str) else "")
except Exception:
    print("")
' "$LEGACY_JSON" "$key"
}

write_legacy_json() {
    local out="$1"
    mkdir -p "$(dirname "$out")"

    declare -A merged=()
    local k prev
    for k in "${COLOR_KEYS[@]}"; do
        if [[ -n "${EXTRACTED[$k]:-}" ]]; then
            merged["$k"]="${EXTRACTED[$k]}"
        else
            prev="$(existing_legacy_value "$k")"
            if [[ -n "$prev" ]] && normalize_hex "$prev" >/dev/null 2>&1; then
                merged["$k"]="$(normalize_hex "$prev")"
            else
                merged["$k"]="${FALLBACK[$k]}"
            fi
        fi
    done

    # Emit JSON (regex extract → structured replace into role map)
    {
        printf '{\n'
        printf '  "_comment": "Ash monochrome (constant) palette. Generated by load-legacy-colors.sh",\n'
        printf '  "_source": "legacy",\n'
        printf '  "_generated": "%s"' "$(date -Iseconds)"
        for k in "${COLOR_KEYS[@]}"; do
            printf ',\n  "%s": "%s"' "$k" "${merged[$k]}"
        done
        printf '\n}\n'
    } > "${out}.tmp"

    python3 -c '
import json, sys
src, dst = sys.argv[1], sys.argv[2]
data = json.load(open(src))
with open(dst, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
' "${out}.tmp" "$out"
    rm -f "${out}.tmp"
}

# Write hyprland/colors.lua + apply live borders from a astral-vagabond role JSON.
# Matches load-wallust-colors.sh: active/pin from accent, chrome stays Ash roles.
apply_hyprland_colors_from_json() {
    local json="$1"
    local out="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprland/colors.lua"
    local triple

    if [[ ! -f "$json" ]]; then
        echo "warning: skip hyprland colors — missing $json" >&2
        return 0
    fi

    if ! triple="$(python3 - "$json" "$out" <<'PY'
import json, sys
from pathlib import Path

src, out = Path(sys.argv[1]), Path(sys.argv[2])
data = json.loads(src.read_text())

def hex6(*keys, fallback="C8C8C8"):
    for key in keys:
        v = str(data.get(key) or "").strip()
        if not v:
            continue
        v = v[1:] if v.startswith("#") else v
        v = v.upper()
        if len(v) == 6 and all(c in "0123456789ABCDEF" for c in v):
            return v.lower()
    return fallback.lower()

active = hex6("borderActive", "accent", fallback="C8C8C8")
idle = hex6("borderIdle", fallback="333333")
bg = hex6("bgPrimary", fallback="121212")

out.parent.mkdir(parents=True, exist_ok=True)
text = f"""hl.config({{
    general = {{
        col = {{
            active_border   = "rgb({active})",
            inactive_border = "rgb({idle})",
        }},
    }},
    misc = {{
        background_color = "rgb({bg})",
    }},
}})

hl.window_rule({{
    match        = {{ pin = 1 }},
    border_color = "rgba({active}AA) rgba({active}77)",
}})
"""
tmp = out.with_suffix(".lua.tmp")
tmp.write_text(text)
tmp.replace(out)
print(f"{active} {idle} {bg}")
PY
)"; then
        echo "warning: failed to write hyprland colors.lua" >&2
        return 0
    fi

    local active idle bg
    read -r active idle bg <<< "$triple"
    echo "hyprland: wrote $out"
    echo "  active_border=rgb(${active})  inactive=rgb(${idle})  bg=rgb(${bg})"

    if command -v hyprctl >/dev/null 2>&1 && hyprctl -j monitors &>/dev/null; then
        hyprctl --batch "\
keyword general:col.active_border rgb(${active}) ;\
keyword general:col.inactive_border rgb(${idle}) ;\
keyword misc:background_color rgb(${bg})" >/dev/null 2>&1 \
            && echo "hyprland: live borders applied (hyprctl)" \
            || echo "warning: hyprctl keyword apply failed" >&2
    else
        echo "hyprland: not running — colors.lua only (apply on next reload)"
    fi
}

# Paint mako + fuzzel from the same role JSON (Ash chrome, wallpaper accents).
apply_theme_clients_from_json() {
    local json="$1"
    local helper="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprland/scripts/apply-theme-clients.sh"
    if [[ ! -x "$helper" ]]; then
        echo "warning: skip mako/fuzzel theme — missing $helper" >&2
        return 0
    fi
    "$helper" "$json" || echo "warning: apply-theme-clients.sh failed" >&2
}

activate_legacy() {
    mkdir -p "$COLORS_DIR"
    if [[ ! -f "$LEGACY_JSON" ]]; then
        echo "error: missing $LEGACY_JSON — run without --activate first" >&2
        exit 1
    fi
    cp -f "$LEGACY_JSON" "${ACTIVE_JSON}.tmp"
    mv -f "${ACTIVE_JSON}.tmp" "$ACTIVE_JSON"
    printf 'legacy\n' > "$SOURCE_FILE"
    echo "activated: legacy → $ACTIVE_JSON"
    apply_hyprland_colors_from_json "$ACTIVE_JSON"
    apply_theme_clients_from_json "$ACTIVE_JSON"
}

status() {
    local src="(none)"
    [[ -f "$SOURCE_FILE" ]] && src="$(tr -d '\n' < "$SOURCE_FILE")"
    echo "astral-vagabond:  $ASTRAL_VAGABOND_DIR"
    echo "source:     $src"
    echo "legacy:     $LEGACY_JSON$([ -f "$LEGACY_JSON" ] && echo ' (ok)' || echo ' (missing)')"
    echo "active:     $ACTIVE_JSON$([ -f "$ACTIVE_JSON" ] && echo ' (ok)' || echo ' (missing)')"
    if [[ -f "$ACTIVE_JSON" ]]; then
        python3 -c '
import json, sys
d = json.load(open(sys.argv[1]))
keys = [k for k in d if not k.startswith("_")]
print(f"roles:      {len(keys)}")
for k in ("bgPrimary", "accent", "textPrimary", "stateSafe"):
    if k in d:
        print(f"  {k:16} {d[k]}")
' "$ACTIVE_JSON"
    fi
}

ACTION="extract-activate"
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help) usage ;;
        --extract) ACTION="extract" ;;
        --activate) ACTION="activate" ;;
        --status) ACTION="status" ;;
        *)
            echo "unknown arg: $1" >&2
            usage
            ;;
    esac
    shift
done

declare -A EXTRACTED=()

case "$ACTION" in
    status)
        status
        ;;
    activate)
        activate_legacy
        status
        ;;
    extract)
        extract_from_theme "$THEME_QML" || true
        write_legacy_json "$LEGACY_JSON"
        echo "wrote: $LEGACY_JSON"
        echo "extracted hardcoded color props from Theme.qml: ${#EXTRACTED[@]}"
        ;;
    extract-activate)
        extract_from_theme "$THEME_QML" || true
        write_legacy_json "$LEGACY_JSON"
        echo "wrote: $LEGACY_JSON"
        echo "extracted hardcoded color props from Theme.qml: ${#EXTRACTED[@]}"
        activate_legacy
        status
        ;;
esac
